=== yashikagoyal98/xml_repo/xmlxsdProject/src/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zensar.com/movies" xmlns:zen="http://www.zensar.com/movies" elementFormDefault="qualified">
<element name="movies">
<complexType>
<sequence>
<element name="movie" maxOccurs="unbounded">
<complexType>
<sequence>
<element name="code">
<simpleType>
<restriction base="int">
<totalDigits value="4"></totalDigits>
<minExclusive value="5001"></minExclusive>
<maxExclusive value="6000"></maxExclusive>
</restriction>
</simpleType>
</element>
<element name="title" type="string"></element>
<element name="release-date" type="date" minOccurs="0" maxOccurs="1"></element>
<element name="theatre-name" maxOccurs="unbounded">
<simpleType>
<restriction base="string">
<minLength value="4"></minLength>
<maxLength value="20"></maxLength></restriction></simpleType></element>
<element name="city" minOccurs="0" maxOccurs="unbounded"></element>
</sequence>
</complexType>
</element>
</sequence>
</complexType>
</element>
</schema>

=== yashikagoyal98/xml_repo/xmlxsdProject/src/moviedetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<zen:movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zen="http://www.zensar.com/movies" xsi:schemaLocation="http://www.zensar.com/movies movies.xsd ">
  <zen:movie>
    <zen:code>5001</zen:code>
    <zen:title>zen:hawda bridge pe latki hui laash</zen:title>
    <zen:theatre-name>zen:PVR Cinemas</zen:theatre-name>
  </zen:movie>
  <zen:movie>
    <zen:code>5002</zen:code>
    <zen:title>zen:yeh jawani hai deewani</zen:title>
    <zen:theatre-name>zen:Inox</zen:theatre-name>
  </zen:movie>
</zen:movies>
